2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Current SDK version is 0.17.8
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Configure stats pid to 8968
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Loading settings from C:\Users\UMI\.config\wandb\settings
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Loading settings from C:\Users\UMI\Desktop\gan\wandb\settings
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Loading settings from environment variables: {}
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Applying setup settings: {'_disable_service': False}
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Inferring run settings from compute environment: {'program_relpath': 'gan.py', 'program_abspath': 'C:\\Users\\UMI\\Desktop\\gan\\gan.py', 'program': 'C:\\Users\\UMI\\Desktop\\gan\\gan.py'}
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_setup.py:_flush():77] Applying login settings: {}
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:_log_setup():524] Logging user logs to C:\Users\UMI\Desktop\gan\wandb\run-20240901_134346-cdlncnwz\logs\debug.log
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:_log_setup():525] Logging internal logs to C:\Users\UMI\Desktop\gan\wandb\run-20240901_134346-cdlncnwz\logs\debug-internal.log
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:init():607] calling init triggers
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:init():614] wandb.init called with sweep_config: {}
config: {}
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:init():657] starting backend
2024-09-01 13:43:46,533 INFO    MainThread:8968 [wandb_init.py:init():661] setting up manager
2024-09-01 13:43:46,537 INFO    MainThread:8968 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-09-01 13:43:46,538 INFO    MainThread:8968 [wandb_init.py:init():669] backend started and connected
2024-09-01 13:43:46,543 INFO    MainThread:8968 [wandb_init.py:init():767] updated telemetry
2024-09-01 13:43:46,544 INFO    MainThread:8968 [wandb_init.py:init():800] communicating run to backend with 90.0 second timeout
2024-09-01 13:43:47,041 ERROR   MainThread:8968 [wandb_init.py:init():826] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-01 13:43:47,041 ERROR   MainThread:8968 [wandb_init.py:init():1238] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\UMI\Desktop\myenv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1228, in init
    return wi.init()
           ^^^^^^^^^
  File "C:\Users\UMI\Desktop\myenv\Lib\site-packages\wandb\sdk\wandb_init.py", line 832, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-09-01 13:43:48,477 WARNING MsgRouterThr:8968 [router.py:message_loop():77] message_loop has been closed
